[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "https://sparkle-dental.netlify.com/*"
  to = "https://www.sparkledental.in/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

# Build Plugins
  [[plugins]]
  package = "netlify-plugin-image-optim"   

  package = "@netlify/plugin-sitemap"
    [plugins.inputs]
    buildDir = "public"
